SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `mzlume` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mzlume` ;

-- -----------------------------------------------------
-- Table `mzlume`.`MZ_CADERNOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_CADERNOS` (
  `CD_CADERNOS` INT NOT NULL AUTO_INCREMENT ,
  `DS_CADERNOS` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_CADERNOS`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_BLOCOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_BLOCOS` (
  `CD_BLOCOS` INT NOT NULL AUTO_INCREMENT ,
  `DS_BLOCOS` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_BLOCOS`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_ACABAMENTOS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_ACABAMENTOS` (
  `CD_ACABAMENTOS` INT NOT NULL AUTO_INCREMENT ,
  `DS_ACABAMENTOS` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_ACABAMENTOS`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_MIOLO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_MIOLO` (
  `CD_MIOLO` INT NOT NULL ,
  `DS_MIOLO` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_MIOLO`) )
ENGINE = InnoDB
COMMENT = '				\n\n	\n	\n	\n	';


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_INSERCOES`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_INSERCOES` (
  `CD_INSERCOES` INT NOT NULL AUTO_INCREMENT ,
  `DS_INSERCOES` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_INSERCOES`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_CAPA_DURA`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_CAPA_DURA` (
  `CD_CAPA_DURA` INT NOT NULL AUTO_INCREMENT ,
  `DS_CAPA_DURA` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_CAPA_DURA`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_PAPEL`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_PAPEL` (
  `CD_PAPEL` INT NOT NULL AUTO_INCREMENT ,
  `DS_PAPEL` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_PAPEL`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_IMPRESSAO_MIOLO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_IMPRESSAO_MIOLO` (
  `CD_IMPRESSAO_MIOLO` INT NOT NULL AUTO_INCREMENT ,
  `DS_IMPRESSAO_MIOLO` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_IMPRESSAO_MIOLO`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mzlume`.`MZ_OS_PRODUCAO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `mzlume`.`MZ_OS_PRODUCAO` (
  `CD_OS_PRODUCAO` INT NOT NULL AUTO_INCREMENT ,
  `CD_CADERNOS` INT NOT NULL ,
  `CD_BLOCOS` INT NOT NULL ,
  `CD_ACABAMENTOS` INT NOT NULL ,
  `CD_MIOLO` INT NOT NULL ,
  `CD_INSERCOES` INT NOT NULL ,
  `CD_CAPA_DURA` INT NOT NULL ,
  `CD_PAPEL` INT NOT NULL ,
  `CD_IMPRESSAO_MIOLO` INT NOT NULL ,
  `DS_CLIENTE` VARCHAR(60) NOT NULL ,
  `NU_QUANTIDADE` INT NOT NULL ,
  `FG_PERCALUX` CHAR(1) NULL ,
  `DS_COR_PERCALUX` VARCHAR(60) NULL ,
  `DS_GRV_PERCALUX` VARCHAR(60) NULL ,
  `QT_IP_LAMINAS` INT NULL ,
  `DS_IP_CORES` VARCHAR(40) NULL ,
  `DS_OUT_INFORMACOES` VARCHAR(255) NULL ,
  `DS_RESPONSAVEL` VARCHAR(60) NOT NULL ,
  `DS_GRAF_RESPONSAVEL` VARCHAR(60) NOT NULL ,
  `CREATED` TIMESTAMP NOT NULL DEFAULT NOW() ,
  PRIMARY KEY (`CD_OS_PRODUCAO`) ,
  INDEX `FK_CADERNO_OS_PRODUCAO` (`CD_CADERNOS` ASC) ,
  INDEX `FK_BLOCOS_OS_PRODUCAO` (`CD_BLOCOS` ASC) ,
  INDEX `FK_ACABAMENTOS_OS_PRODUCAO` (`CD_ACABAMENTOS` ASC) ,
  INDEX `FK_MIOLO_OS_PRODUCAO` (`CD_MIOLO` ASC) ,
  INDEX `FK_INSERCOES_OS_PRODUCAO` (`CD_INSERCOES` ASC) ,
  INDEX `FK_CAPA_DURA_OS_PRODUCAO` (`CD_CAPA_DURA` ASC) ,
  INDEX `FK_PAPEL_OS_PRODUCAO` (`CD_PAPEL` ASC) ,
  INDEX `fk_MZ_OS_PRODUCAO_MZ_IMPRESSAO_MIOLO1` (`CD_IMPRESSAO_MIOLO` ASC) ,
  CONSTRAINT `FK_CADERNO_OS_PRODUCAO`
    FOREIGN KEY (`CD_CADERNOS` )
    REFERENCES `mzlume`.`MZ_CADERNOS` (`CD_CADERNOS` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_BLOCOS_OS_PRODUCAO`
    FOREIGN KEY (`CD_BLOCOS` )
    REFERENCES `mzlume`.`MZ_BLOCOS` (`CD_BLOCOS` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ACABAMENTOS_OS_PRODUCAO`
    FOREIGN KEY (`CD_ACABAMENTOS` )
    REFERENCES `mzlume`.`MZ_ACABAMENTOS` (`CD_ACABAMENTOS` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MIOLO_OS_PRODUCAO`
    FOREIGN KEY (`CD_MIOLO` )
    REFERENCES `mzlume`.`MZ_MIOLO` (`CD_MIOLO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INSERCOES_OS_PRODUCAO`
    FOREIGN KEY (`CD_INSERCOES` )
    REFERENCES `mzlume`.`MZ_INSERCOES` (`CD_INSERCOES` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CAPA_DURA_OS_PRODUCAO`
    FOREIGN KEY (`CD_CAPA_DURA` )
    REFERENCES `mzlume`.`MZ_CAPA_DURA` (`CD_CAPA_DURA` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PAPEL_OS_PRODUCAO`
    FOREIGN KEY (`CD_PAPEL` )
    REFERENCES `mzlume`.`MZ_PAPEL` (`CD_PAPEL` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MZ_OS_PRODUCAO_MZ_IMPRESSAO_MIOLO1`
    FOREIGN KEY (`CD_IMPRESSAO_MIOLO` )
    REFERENCES `mzlume`.`MZ_IMPRESSAO_MIOLO` (`CD_IMPRESSAO_MIOLO` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
